generator:
  class: sfDoctrineGenerator
  param:
    model_class:           SignosVitalesNursery
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          signos_vitales_nursery
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
        title: Signos Vitales Nursery
        display: [hora, fc_nursery, fr_nursery, to_nursery]
        actions: {}
        batch_actions: {}
      filter:  
        display: [hora, fc_nursery, fr_nursery, to_nursery]
      form:    ~
      edit:    
        title: Editar Signos Vitales Nursery
        actions:
          _save: ~
      new:     
        title: Nuevo Signos Vitales Nursery
        actions:
          _save: ~
          _save_and_add: ~