generator:
  class: sfDoctrineGenerator
  param:
    model_class:           OrdenMedica
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          orden_medica
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
        title: Ordenes Médicas
        actions: {}
        batch_actions: {}
      filter:  
        display: [numero_hoja]
      form:    ~
      edit:    ~
      new:     ~
