generator:
  class: sfDoctrineGenerator
  param:
    model_class:           OrdenMedica
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          orden_medica
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
        nombre_medicamento_indicacion: {label: Indicaciones}
        via_administracion:            {label: Administracion}
        dosis_intervalo:               {label: Intervalo}
        fecha_inicio:                  {label: Inicio}
        fecha_terminacion:             {label: Termino}
      list:    
        title: Ordenes Médicas
        display: [nombre_medicamento_indicacion, via_administracion, dosis_intervalo, fecha_inicio, fecha_terminacion]
        actions: {}
        batch_actions: {}
      filter:  ~
      form:    ~
      edit:    
        actions:
          _save: ~
      new:     
        actions:
          _save: ~
          _save_and_add: ~