generator:
  class: sfDoctrineGenerator
  param:
    model_class:           ProgramacionCirugias
    theme:                 dojotheme
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          programacion_cirugias
    with_doctrine_route:   true
    actions_base_class:    sfActions
    dojo_object:   symfonydojo
    config:
      actions: ~
      fields: ~
#        operacion_fecha: { name: fecha de operacion, type: plain }           
      list:    
        actions: {}
        batch_actions: {}       
      filter:  
        display: [ medico_id, operacion_fecha ]
      form:    ~
      edit:    ~
      new: 
        title: Nueva Programacion Cirugia      