generator:
  class: sfDoctrineGenerator
  param:
    model_class:           AutorizacionAltaSolicitada
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          autorizacion_alta_solicitada
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
        title: Lista de Autorizaciones de Altas Solicitadas
        actions: {}
        batch_actions: {}
      filter:  
        class: false
      form:    ~
      edit:    ~
      new:     
        actions:
          _save: ~
          _save_and_add: ~
