generator:
  class: sfDoctrineGenerator
  param:
    model_class:           AtencionEnfermeria
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          atencion_enfermeria
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
        title: Atencion de Enfermeria
        actions: {}
        batch_actions: {}
      filter:  
        class: false
      form:    ~
      edit:    
        title: Editar Atencion %%%%
      new:     
        title: Nueva atencion de Enfermeria
        actions:
          _save: ~
          _save_and_add: ~
