generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Apgar
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          apgar
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
        nacer_egresar: {label: 'Recien Nacido?'}
      list:    
        title: APGAR
        actions: {}
        batch_actions: {}
      filter:  
        display: [nacer_egresar]
      form:    ~
      edit:    
        Editar Registro Apgar
      new:     
        title: Registro Apgar
        actions:
          _save: ~
          _save_and_add: ~
