generator:
  class: sfDoctrineGenerator
  param:
    model_class:           SolicitudServicio
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          solicitud_servicio
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
        title: Solicitudes de Servicios
        display: [atencion_id, para, diagnostico_presuncion]
        actions: {}
        batch_actions: {}
      filter:  
        display: [atencion_id]
      form:    ~
      edit:    
        title: Editar Solicitud de Servicio
        actions:
          _save: ~
      new:     
        title: Nueva Solicitud de Servicios
        actions:
          _save: ~
          _save_and_add: ~