generator:
  class: sfDoctrineGenerator
  param:
    model_class:           NotasEnfermeria
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          notas_enfermeria
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
        title: Notas de Enfermeria
        display: [fecha, hora, procedimientos]
        actions: {}
        batch_actions: {}
      filter:  
        display: [fecha]
      form:    ~
      edit:    
        title: Editar Nota de Enfermeria
        actions:
          _save: ~
      new:     
        title: Nueva Nota de Enfermeria
        actions:
          _save: ~
          _save_and_add: ~