generator:
  class: sfDoctrineGenerator
  param:
    model_class:           SolicitudInterconsulta
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          solicitud_interconsulta
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
        title: Solicitudes de Interconsulta
        display: [dirigida_a, especialidad, motivo]
        actions: {}
        batch_actions: {}
      filter:  
        display: [dirigida_a, especialidad]
      form:    ~
      edit:    
        title: Editar Solicitud de Interconsulta
        actions:
          _save: ~
      new:     
        title: Nueva Solicitud de Interconsulta
        actions:
          _save: ~
          _save_and_add: ~