generator:
  class: sfDoctrineGenerator
  param:
    model_class:           SolicitudInterconsulta
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          solicitud_interconsulta
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
        actions: {}
        batch_actions: {}
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
