generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Atencion
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          atencion
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
        title: Lista de Atenciones
        actions: {}
        batch_actions: {}
      filter:  
        display: [nombre]
      form:    ~
      edit:    
        title: Editar Atencion %%nombre%%
      new:    
        title: Nueva Atencion
