generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Atencion
    theme:                 dojotheme
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          atencion
    with_doctrine_route:   true
    actions_base_class:    sfActions
    extra_url_custom_id:   internado_id

    config:
      actions: ~
      fields:  ~
      list:    
        title: Lista de Atenciones
        actions: {}
        batch_actions: {}
      filter:  
        display: [nombre]
      form:    ~
      edit:    
        title: Editar Atencion %%nombre%%
      new:    
        title: Nueva Atencion
        actions:
          _save: ~
          _save_and_add: ~
