generator:
  class: sfDoctrineGenerator
  param:
    model_class:           ExamenFisicoRecienNacido
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          examen_fisico_recien_nacido
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
        title: Examen Físico del Recien Nacido
        display: [ap_paterno, ap_materno, sexo, peso_nacimiento]
        actions: {}
        batch_actions: {}
      filter:  
        display: [ap_paterno, ap_materno, sexo]
      form:    ~
      edit:    
        title: Editar Recien Nacido %%ap_paterno%% %%ap_materno%%
        actions:
          _save: ~
      new:     
        title: Nuevo Recien Nacido
        actions:
          _save: ~
          _save_and_add: ~