generator:
  class: sfDoctrineGenerator
  param:
    model_class:           SolicitudReposicionMaterial
    theme:                 dojotheme
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          solicitud_reposicion_material
    with_doctrine_route:   true
    actions_base_class:    sfActions
    extra_url_custom_id:   internado_id

    config:
      actions: ~
      fields:  ~
      list:    
        title: Solicitudes de Reposicion de Material
        display: [unidad, encargado]
        actions: {}
        batch_actions: {}
      filter:  
        display: [unidad, encargado]
      form:    ~
      edit:    
        title: Editar Solicitud de Reposicion de Material
        actions:
          _save: ~
      new:     
        title: Nueva Solicitud de Reposicion de Material
        actions:
          _save: ~
          _save_and_add: ~